name: Build and Release Firmware

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Determine if this is a release
        id: release_check
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "release=true" >> $GITHUB_OUTPUT
          else
            echo "release=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate semantic version (only for release)
        if: steps.release_check.outputs.release == 'true'
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "^(feat|fix|refactor)!:"
          minor_pattern: "^feat:"
          search_commit_body: true

      - name: Export version
        if: steps.release_check.outputs.release == 'true'
        run: |
          echo "MAJOR=$(echo '${{ steps.semver.outputs.version }}' | cut -d. -f1)" >> $GITHUB_ENV
          echo "MINOR=$(echo '${{ steps.semver.outputs.version }}' | cut -d. -f2)" >> $GITHUB_ENV
          echo "PATCH=$(echo '${{ steps.semver.outputs.version }}' | cut -d. -f3)" >> $GITHUB_ENV

      - name: Set fallback version for test builds
        if: steps.release_check.outputs.release != 'true'
        run: |
          echo "MAJOR=0" >> $GITHUB_ENV
          echo "MINOR=0" >> $GITHUB_ENV
          echo "PATCH=0" >> $GITHUB_ENV

      - name: Run PlatformIO build
        run: |
          platformio run

      - name: Archive firmware binaries
        if: steps.release_check.outputs.release == 'true'
        run: |
          mkdir -p dist
          for dir in .pio/build/*; do
            cp "$dir/firmware.bin" "dist/$(basename $dir)-firmware-v${{ steps.semver.outputs.version }}.bin" || true
          done

      - name: Generate Release Notes
        if: steps.release_check.outputs.release == 'true'
        id: release_notes
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');

            let latestTag = '';
            try {
              latestTag = execSync('git describe --tags --abbrev=0').toString().trim();
            } catch {
              latestTag = '';
            }

            let commitLog = '';
            if (latestTag) {
              commitLog = execSync(`git log ${latestTag}..HEAD --pretty=format:"- %s"`).toString();
            } else {
              commitLog = execSync('git log --pretty=format:"- %s"').toString();
            }

            // Zugriff auf PR-Beschreibung
            let prText = '';
            if (context.payload.pull_request) {
              prText = context.payload.pull_request.body || '';
            }

            const notes = `${prText ? prText + '\n\n---\n\n' : ''}${commitLog}`;
            core.setOutput('body', notes);

      - name: Create GitHub Release
        if: steps.release_check.outputs.release == 'true' && steps.semver.outputs.version != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.semver.outputs.version }}
          name: Release v${{ steps.semver.outputs.version }}
          body: ${{ steps.release_notes.outputs.body }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
