name: Release Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Install PlatformIO libraries
        run: pio lib install

      - name: Run PlatformIO build
        run: platformio run

      - name: Generate release version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "^(feat|fix|refactor)!:"
          minor_pattern: "^feat:"
          search_commit_body: true

      - name: Log version
        run: echo "Version is ${{ steps.semver.outputs.version }}"

      - name: Archive firmware binaries
        run: |
          mkdir -p dist
          cp .pio/build/*/firmware*.bin dist/ || true
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: steps.semver.outputs.version != ''
        with:
          tag_name: v${{ steps.semver.outputs.version }}
          name: Release v${{ steps.semver.outputs.version }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
